[package]
name = "cheese-shop"
version = "0.2.0"
authors = ["Adam Shirey <adam@shirey.ch>"]
edition = "2021"

[lib]
name = "CheeseShop"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
