[package]
name = "cheese-shop"
version = "0.2.0"
authors = ["adam"]
edition = "2018"

[lib]
name = "CheeseShop"
crate-type = ["cdylib"]


[dependencies.pyo3]
version = "0.11.0"
#features = ["extension-module"]
extension-module = ["extension-module"]
default = ["extension-module"]
